@host = http://localhost:8080/fhir

@folder = unicom

### see if server OK 
GET {{host}}/metadata


### Post patient data 
POST {{host}}/ HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./ips-data2.json



### get summary
GET {{host}}/Patient/6658a702-0d9d-4f1d-db59-b8310000000a/$summary HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0



### test patient data JIC 
POST {{host}}/Bundle/$validate HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./ips-data2.json






### Post working patient data 
POST {{host}}/ HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./ips-data.json


### get summary
GET {{host}}/Patient/2b90dd2b-2dab-4c75-9bb9-a355e07401e8/$summary HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0


